name: Deploy Discord Bot to VM

# This workflow runs on two conditions:
    # 1. A push event to the 'main' branch.
    # 2. A 'workflow_dispatch' event, which adds a "Run workflow" button on the Actions tab.

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy:
        # Tell GitHub to send this job to any available runner with the 'self-hosted' label.
        runs-on: self-hosted

        steps:
            # Step 1: Check out the repository code into the runner's working directory on the VM.
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Run the deployment commands directly on the VM's shell.
            - name: Deploy Bot
              run: |
                echo "--- Starting deployment on self-hosted runner ---"

                # Use rsync to mirror the repository to the project directory.
                # CRITICAL: --exclude-from='.gitignore' prevents rsync from deleting
                # secrets, logs, and virtual environment on the server.
                rsync -av --delete --exclude-from='.gitignore' ./ /home/makerspace/DiscProdSheetify/

                echo "--- Code synchronized to project directory ---"

                # Run the commands from within the actual project directory.
                cd /home/makerspace/DiscProdSheetify
              
                echo "--- Installing dependencies ---"
                /home/makerspace/.local/bin/uv sync

                echo "--- Restarting service ---"
                sudo systemctl restart DiscProdSheetify.service
          
                echo "--- Deployment complete ---"